---
- name: Deploy Rook Ceph Operator
  hosts: bastion
  connection: local
  gather_facts: false

  vars:
    test: "Install the Ceph operator"

  tasks:
    - name: Greetings
      debug:
        msg: "Tasks to configure OCP cluster {{ ocp_api }} for: {{ test }}"

    # - name: Apply Rook Operator manifests
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /path/to/rook-ceph/cluster/examples/kubernetes/ceph/operator.yaml
    #   register: rook_operator

    # - name: Apply Ceph cluster manifests
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /path/to/rook-ceph/cluster/examples/kubernetes/ceph/cluster.yaml
    #   register: ceph_cluster

    # - name: Create a StorageClass for Ceph RBD
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /path/to/rook-ceph/cluster/examples/kubernetes/ceph/storageclass.yaml
    #   register: rbd_storageclass

    # - name: Create a Ceph Object Store
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /path/to/rook-ceph/cluster/examples/kubernetes/ceph/object-store.yaml
    #   register: object_store

    - name: Login to Hub cluster
      shell: echo "y" | oc login -u kubeadmin -p {{ ocpw }} --server={{ ocp_api_url }} --insecure-skip-tls-verify=true
      no_log: true

    - name: Add Rook Helm repository
      kubernetes.core.helm_repository:
        name: rook-release
        repo_url: "https://charts.rook.io/release"
        state: present
      register: helm_repo_result

    - name: Install Rook Ceph operator using Helm
      kubernetes.core.helm:
        name: rook-ceph
        chart_ref: rook-release/rook-ceph
        release_namespace: rook-ceph
        create_namespace: true
        values:
          # Customize your Rook Ceph installation here
          # Example:
          # operatorNamespace: rook-ceph
          # cephClusterSpec:
          #   ...
        state: present

    # Show result 
    - name: Show Ceph Operator release in namespace
      shell: helm ls --namespace rook-ceph

    #Install Rook Ceph cluster CRD using Helm
    - name: Install Rook Ceph cluster CRD using Helm
      kubernetes.core.helm:
        name: rook-ceph-cluster
        chart_ref: rook-release/rook-ceph-cluster
        release_namespace: rook-ceph
        values_files:
          - ./files/rook-ceph-cluster-values.yaml
        state: present


    # Show result 
    - name: Show Ceph Operator and Ceph Cluster (CRD) in namespace
      shell: helm ls --namespace rook-ceph
