- name: Patch ROTA attribute for OCP on Fyre stack
  hosts: bastion
  connection: local
  gather_facts: false
  module_defaults:
#  redhat.openshift.openshift:
#    host: https://{{ ocp_api }}:6443
#    ca_cert: ca.pem       
#  become: true

  vars:
    test: "Patch ROTA attribute for OCP on Fyre stack"

  tasks:
    - name: Greetings
      debug:
        msg: "Tasks to configure OCP for: {{ test }}"


    - name: Log in (obtain access token)
      redhat.openshift.openshift_auth:
        host: "{{ ocp_api_url }}"
        username: "kubeadmin"
        password: "{{ ocpw }}"
        validate_certs: false
      register: openshift_auth_results

# Apply MachineConfig 'worker-udev-configuration'
    # - name: Apply worker-udev-configuration to change the ROTA attribute of node's extra disks (vdb, vdc) 
    #   kubernetes.core.k8s:
    #     state: present
    #     src: ./files/worker-udev-configuration.yml

#    - name: Wait some minutes until all workers have been rebooted
#       kubernetes.core.k8s_info:
#         api_version: rbac.authorization.k8s.io/v1
#         kind: Node
#         metadata.labels.node-role.kubernetes.io/worker: ""
# status.conditions.type.ready
# #        name: open-cluster-management:subscription-admin
#         wait: yes
#         wait_sleep: 10
#         wait_timeout: 360
      # kubernetes.core.k8s_info:
      #   kind: Node
      #   name: worker0.{{ clustername }}.cp.fyre.ibm.com
      #   state: absent
#        field_selectors:
#          - status.conditions.type: "Ready"
#            status.conditions.status: "True"
   #     wait: yes
        # wait_condition: 
        #   status.conditions.type: "Ready"
        #   status.conditions.status: "False"
#      register: node_list1
#      until: pod_list1|json_query('resources[*].status.phase')|unique == ["Running"]
      # retries: 3
      # #60
      # delay: 2

    - name: Wait for worker0 node to be ready
      kubernetes.core.k8s_info:
        kind: Node
        name: worker0.{{ clustername }}.cp.fyre.ibm.com
        wait: yes
        wait_condition:
          reason: KubeletReady
          type: Ready
          status: "False"
        wait_timeout: 10
        wait_sleep: 2    
        retries: 3  