---
- name: Configure OCP
  hosts: localhost
  become: true

  vars_files:
    - group_vars/web.yml

  vars:
    - test: "Hallo"

  tasks:
    - name: Display the config
      debug:
        msg: "Ich sag mal {{ test }}"

    - name: test shell command
      shell: echo "This command runs on "$(hostname)
 

    - name: Create a k8s namespace
      k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present