---
- name: Configure OCP
  hosts: bastion
  connection: local
  gather_facts: false
  module_defaults:
#  redhat.openshift.openshift:
#    host: https://{{ ocp_api }}:6443
#    ca_cert: ca.pem       
#  become: true

  vars_files:
    - group_vars/web.yml

  vars:
    - test: "Hallo"

  tasks:
    - name: Greetings
      debug:
        msg: "Ich sag mal {{ test }}"
        msg: "Das ocpw lautet {{ ocpw }}"

    - name: test shell command
      shell: echo "This command runs on "$(hostname)
 
    - name: Get environment variable from the shell
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."

    - name: Login to Hub cluster
      shell: oc login -u kubeadmin -p {{ ocpw }} --server={{ ocp_api_url }} --insecure-skip-tls-verify=true

    - name: Log in (obtain access token)
      redhat.openshift.openshift_auth:
        host: "{{ ocp_api_url }}"
        username: "kubeadmin"
        password: "{{ ocpw }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Create a k8s namespace
      k8s:
        state: present
        name: openshift-gitops-operator
        api_version: v1
        kind: Namespace
        resource_definition:
          metadata:
            labels: 
              openshift.io/cluster-monitoring=true
 
