apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gitops-operator
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-gitops-install
        spec:
          operatorGroup: 
              name: gitops-opgroup
              namespace: openshift-gitops
          versions: 
            - openshift-gitops-operator.v1.13.1
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: gitops-1.13
            installPlanApproval: Automatic
            name: openshift-gitops-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gitops-operator
  namespace: rhacm-policies
placementRef:
  name: test-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io 
subjects:
- name: policy-gitops-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io