apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cert-manager-operator
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cert-manager-operator
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: cert-manager-operator
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-cert-manager-operator
                  namespace: cert-manager-operator
                spec:
                  targetNamespaces: []
                  spec: {}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-cert-manager-operator
                  namespace: cert-manager-operator
                spec:
                  channel: stable-v1
                  name: openshift-cert-manager-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  installPlanApproval: Automatic
          remediationAction: enforce
          severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cert-manager-operator
  namespace: rhacm-policies
placementRef:
  name: test-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io 
subjects:
- name: policy-cert-manager-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io