apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: initial-gitops-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - product: acm-operator 
        cluster: acm-hub
        url: https://kubernetes.default.svc
        wave: 0
      - product: acm-multiclusterhub
        cluster: acm-hub
        url: https://kubernetes.default.svc
        wave: 1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
      name: '{{.product}}-install'
    spec:
      syncPolicy:
        automated: {}
      project: default
      source:
        repoURL: https://github.com/entgelme/OCPAutomation.git
        targetRevision: HEAD
        path: Install/{{.product}}/
      destination:
        server: '{{.url}}'
        namespace: acm-hub
