apiVersion: v1
items:
- apiVersion: local.storage.openshift.io/v1alpha1
  kind: LocalVolumeDiscovery
  metadata:
    creationTimestamp: "2024-07-03T14:17:12Z"
    generation: 1
    name: auto-discover-devices
    namespace: openshift-local-storage
    resourceVersion: "59129861"
    uid: 364187dc-42a7-4ef9-91ea-481e219af216
  spec:
    nodeSelector:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists
kind: List
metadata:
  resourceVersion: ""           