apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
 name: local-block
 namespace: openshift-local-storage
spec:
 nodeSelector:
   nodeSelectorTerms:
     - matchExpressions:
         - key: cluster.ocs.openshift.io/openshift-storage
           operator: Exists
 storageClassName: localblock
 volumeMode: Block
 fstype: ext4
 maxDeviceCount: 1  # <-- Maximum number of devices per node to be used
 deviceInclusionSpec:
   deviceTypes:
   - disk
   - part   # <-- Remove this if not using partitions
   minSize: 100Gi   # <-- Uncomment and modify to limit the minimum size of disk used
   #maxSize: 0Ti   # <-- Uncomment and modify to limit the maximum size of disk used

