apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mcg-operator.1-openshift-storage: ""
  name: mcg-operator-stable-4.14-redhat-operators-openshift-marketplace
  namespace: 1-openshift-storage
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Subscription
    name: odf-operator
spec:
  channel: stable-4.14
  installPlanApproval: Automatic
  name: mcg-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
