apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: "true"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  creationTimestamp: "2024-02-22T08:48:30Z"
  finalizers:
  - storagecluster.ocs.openshift.io
  generation: 2
  name: ocs-storagecluster
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: odf.openshift.io/v1alpha1
    kind: StorageSystem
    name: ocs-storagecluster-storagesystem
    uid: 778ff8d3-ea50-499b-9be2-76897aba1f9b
  resourceVersion: "519860"
  uid: 23dc2daf-b689-4f24-990e-5b170edf95aa
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  flexibleScaling: true
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephRBDMirror: {}
    cephToolbox: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  network:
    connections:
      encryption: {}
    multiClusterService: {}
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    count: 6
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset-localblock
    placement: {}
    preparePlacement: {}
    replica: 1
    resources: {}
status:
  conditions:
  - lastHeartbeatTime: "2024-02-22T08:48:31Z"
    lastTransitionTime: "2024-02-22T08:48:31Z"
    message: Version check successful
    reason: VersionMatched
    status: "False"
    type: VersionMismatch
  - lastHeartbeatTime: "2024-02-22T14:02:18Z"
    lastTransitionTime: "2024-02-22T08:50:51Z"
    message: Reconcile completed successfully
    reason: ReconcileCompleted
    status: "True"
    type: ReconcileComplete
  - lastHeartbeatTime: "2024-02-22T14:02:18Z"
    lastTransitionTime: "2024-02-22T08:51:50Z"
    message: Reconcile completed successfully
    reason: ReconcileCompleted
    status: "True"
    type: Available
  - lastHeartbeatTime: "2024-02-22T14:02:18Z"
    lastTransitionTime: "2024-02-22T10:02:04Z"
    message: Reconcile completed successfully
    reason: ReconcileCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2024-02-22T14:02:18Z"
    lastTransitionTime: "2024-02-22T08:48:31Z"
    message: Reconcile completed successfully
    reason: ReconcileCompleted
    status: "False"
    type: Degraded
  - lastHeartbeatTime: "2024-02-22T14:02:18Z"
    lastTransitionTime: "2024-02-22T10:02:04Z"
    message: Reconcile completed successfully
    reason: ReconcileCompleted
    status: "True"
    type: Upgradeable
  failureDomain: host
  failureDomainKey: kubernetes.io/hostname
  failureDomainValues:
  - worker0.cp4bamig1c.cp.fyre.ibm.com
  - worker1.cp4bamig1c.cp.fyre.ibm.com
  - worker2.cp4bamig1c.cp.fyre.ibm.com
  images:
    ceph:
      actualImage: registry.redhat.io/rhceph/rhceph-6-rhel9@sha256:9fe3736781784da48ea5605370a0d497087162105a42e19d1fbada54757e3f44
      desiredImage: registry.redhat.io/rhceph/rhceph-6-rhel9@sha256:9fe3736781784da48ea5605370a0d497087162105a42e19d1fbada54757e3f44
    noobaaCore:
      actualImage: registry.redhat.io/odf4/mcg-core-rhel9@sha256:371a591c7bf1e1f2b1539e9b286aa49bfe8b265126dc3a1178877988f5a0e8fd
      desiredImage: registry.redhat.io/odf4/mcg-core-rhel9@sha256:371a591c7bf1e1f2b1539e9b286aa49bfe8b265126dc3a1178877988f5a0e8fd
    noobaaDB:
      actualImage: registry.redhat.io/rhel8/postgresql-12@sha256:cd5b8cb243a0b233a08bdf807df7bc6192a18e1dc322789d6d2e064e9721d8f0
      desiredImage: registry.redhat.io/rhel8/postgresql-12@sha256:cd5b8cb243a0b233a08bdf807df7bc6192a18e1dc322789d6d2e064e9721d8f0
  kmsServerConnection: {}
  nodeTopologies:
    labels:
      kubernetes.io/hostname:
      - worker0.cp4bamig1c.cp.fyre.ibm.com
      - worker1.cp4bamig1c.cp.fyre.ibm.com
      - worker2.cp4bamig1c.cp.fyre.ibm.com
  phase: Ready
  relatedObjects:
  - apiVersion: ceph.rook.io/v1
    kind: CephCluster
    name: ocs-storagecluster-cephcluster
    namespace: openshift-storage
    resourceVersion: "519410"
    uid: 683cbb2d-1f5a-4c0a-8463-b32c28c67377
  - apiVersion: noobaa.io/v1alpha1
    kind: NooBaa
    name: noobaa
    namespace: openshift-storage
    resourceVersion: "519856"
    uid: 99cb4ec9-4b3b-4ae1-95bd-c5a8b7a724a2
  version: 4.14.4
