apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/odf-csi-addons-operator.1-openshift-storage: ""
  name: odf-csi-addons-operator-stable-4.14-redhat-operators-openshift-marketplace
  namespace: 1-openshift-storage
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Subscription
    name: odf-operator
spec:
  channel: stable-4.14
  config:
    tolerations:
    - effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
  installPlanApproval: Automatic
  name: odf-csi-addons-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
