apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: {{ .Values.clusterset.name }}
    environment: {{ .Values.cluster.environment }}
  annotations: {}
spec:
  hubAcceptsClient: true

