apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-openshift-virtualization-operator
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-openshift-virtualization-operator
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-cnv
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: kubevirt-hyperconverged-group
                  namespace: openshift-cnv
                spec:
                  targetNamespaces:
                    - openshift-cnv
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: hco-operatorhub
                  namespace: openshift-cnv
                spec:
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  name: kubevirt-hyperconverged
                  startingCSV: kubevirt-hyperconverged-operator.v4.19.0
                  channel: "stable" 
          remediationAction: enforce
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: kubevirt-hyperconverged
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: hco.kubevirt.io/v1beta1
                kind: HyperConverged
                metadata:
                  name: kubevirt-hyperconverged
                  namespace: openshift-cnv
                spec:
          remediationAction: inform
          severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-openshift-virtualization-operator
  namespace: rhacm-policies
placementRef:
  name: hub-cluster
  kind: Placement
  apiGroup: cluster.open-cluster-management.io 
subjects:
- name: policy-openshift-virtualization-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io