apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: rhacm-policies
    openshift.io/cluster-monitoring: "true"
  name: rhacm-policies
spec:
  finalizers:
  - kubernetes